### ISSUE TITLE
Expecting an object with a field named `Slot` at _.tasks

### ISSUE THREAD

**Issue by hamsterready** [charypar/swarm-dashboard#2]
Hi,

I tried to run the dashboard on my stack but what I see is:

```
Expecting an object with a field named `Slot` at _.tasks[47] but instead got: {"ID":"xdiylpvef7g4hwf1xu8payis1","Version":{"Index":7650},"CreatedAt":"2017-05-17T12:43:07.838322375Z","UpdatedAt":"2017-05-17T12:43:14.386910711Z","Spec":{"ContainerSpec":{"Image
```

My docker version:

```
$ docker --version
Docker version 17.03.1-ce, build c6d412e
```

BTW, keep the good work :)

**Comment by charypar** [comment]
I think it's currently unfortunately highly dependent on the version of the Docker engine API in use. I even had slight trouble when my docker updated from 1.28 to 1.29.

Can you post the output of `docker version` (rather than `--version`), please?

**Comment by charypar** [comment]
Is that the whole error you're seeing? (Because It looks cut off at the end)

**Comment by hamsterready** [comment]
Here's `docker version`:

```
hamster in ~ λ docker version                                         
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Re error I see, I will try to fire it up again soon and let you know.

**Comment by time4tea** [comment]
I saw the same issue. The error occurred when I had a service with deploy: mode: global

```Expecting an object with a field named `Slot` at _.tasks[9] but instead got: {"ID":"z7imbkxafy2si3ale7190vid9","Version":{"Index":2069},"CreatedAt":"2017-05-30T16:03:21.797247703Z","UpdatedAt":"2017-05-30T16:03:23.362625385Z","Labels":{},"Spec":{"ContainerSpec":{"Image":"xxxxxx:5000/gliderlabs/logspout:latest@sha256:9a807db8e9e484920c3228770da76b8af68e8704d8ca0965e68bf8cefc93cee1","Labels":{"com.docker.stack.namespace":"services"},"Mounts":[{"Type":"bind","Source":"/var/run/docker.sock","Target":"/var/run/docker.sock"}]},"Resources":{},"Placement":{},"ForceUpdate":0},"ServiceID":"x3l2u72d1s46u7r63atoqgnt6","NodeID":"lmx4auhwhme5ccsgf4wlf31pd","Status":{"Timestamp":"2017-05-30T16:03:23.307605241Z","State":"running","Message":"started","ContainerStatus":{"ContainerID":"9c9121212e117a3c98cf971155102f6c370a77bd20ec14019d8b0f5bb8a2fd39","PID":8004},"PortStatus":{}},"DesiredState":"running","NetworksAttachments":[{"Network":{"ID":"i3ebp7vqkiqy1iirzgnjzv59e","Version":{"Index":2022},"CreatedAt":"2017-05-30T15:33:48.580722378Z","UpdatedAt":"2017-05-30T15:33:48.581645766Z","Spec":{"Name":"services_default","Labels":{"com.docker.stack.namespace":"services"},"DriverConfiguration":{"Name":"overlay"},"IPAMOptions":{"Driver":{}}},"DriverState":{"Name":"overlay","Options":{"com.docker.network.driver.overlay.vxlanid_list":"4097"}},"IPAMOptions":{"Driver":{"Name":"default"},"Configs":[{"Subnet":"10.0.0.0/24","Gateway":"10.0.0.1"}]}},"Addresses":["10.0.0.7/24"]}]}```

**Comment by charypar** [comment]
Thanks @time4tea, that really helps narrow it down. I should hopefully be able to reproduce it now.

**Comment by time4tea** [comment]
That was quick!
